version: '3.10'

services:
  python:
    container_name: python
    build: .
    command: sh -c "alembic upgrade head & uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/user_management
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_management
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/var/lib/redis/data

volumes:
  postgres_data:
  redis_data:
